title: "Artheral"
description: "Cyber Security Specialist • OSINT • Threat Hunting • Pentesting"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
google_analytics: true
